export const AuthorDetails = {
  name: "Shaik Mohammad Shahbaaz Alam",
  title: "Full Stack Engineer",
  other_titles: ["Frontend Developer, Backend Developer, Full Stack Developer"],
  skills: {
    current: [
      "angular",
      "angularMaterial",
      "javascript",
      "typescript",
      "react",
      "next",
      "tailwind",
      "node",
      "express",
      "nest",
      "mongo",
      "postgres",
      "jest",
      "cplus",
      "java",
    ],
    frontend: [
      "html",
      "css",
      "javascript",
      "typescript",
      "bootstrap",
      "angular",
      "angularmaterial",
      "react",
      "next",
      "scss",
      "tailwind",
      "materialui",
    ],

    backend: ["node", "express", "nest", "springboot"],
    database: ["mongo", "postgres", "mysql", "firebase"],
    multiMedia: [
      "photoshop",
      "illustrator",
      "figma",
      "premierepro",
      "aftereffects",
    ],
    other: [
      "SEO",
      "a11y",
      "i18n",
      "Jest",
      "git",
      "github",
      "Jasmine",
      "Karma",
      "Clang",
      "Cplus",
      "java",
      "javascript",
      "typescript",
      "docker",
      "vercel",
    ],
  },
};
